# Generated by Django 3.2.9 on 2021-11-23 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enroll', models.DateField()),
                ('date_close', models.DateField()),
                ('score', models.IntegerField()),
                ('id_course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('id_student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
    ]
