# Generated by Django 3.2.9 on 2021-11-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_auto_20211123_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='id_course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='id_student',
        ),
    ]
